### ISSUE TITLE
About the "get_data_MRI"

### ISSUE THREAD

**Issue by qinhuangdaoStation** [jibikbam/CNN-3D-images-Tensorflow#10]
I do not wanna your MRI data. I am just learing the application fo 3D-CNN. But I am not experienced. 
So, Can you give me the code about the "get_data_MRI" without your critical. And at least incluing the format(input, output), code of batch-generate and so on.
I would appreciate it if you could share this code. Looking froward to you reply.

**Comment by jibikbam** [comment]
Sorry about the confusion. I meant to indicate get_data_jpeg defined in input_3Dimage.py. It's fixed now. Thanks.
