### ISSUE TITLE
Can you upload a trained network, rather than just the code?

### ISSUE THREAD

**Issue by mhirsc** [jibikbam/CNN-3D-images-Tensorflow#13]
Hello! I have my own 3D MRI images in NIFTI format that I would like to classify and I would be very grateful if you could upload a trained network that I can feed my own images into rather than just the code to create the network (which does look good, though, I've used similar code in the past). Is this possible?

**Comment by jibikbam** [comment]
It's a good suggestion and I understand your thoughts. Although, I am not sure whether sharing a model trained on patients' medical data without proper agreements is allowed. Do you have a clue?
