### ISSUE TITLE
the form of data and labels

### ISSUE THREAD

**Issue by wanqiuwang** [jibikbam/CNN-3D-images-Tensorflow#15]
I want to know the form of your data and labels. Can you please take a picture or list it?

**Comment by xingjianzhang1997** [comment]
I also want to know the form of your data and labels. Can you please take a picture or list it？ I don't know how to form my data

**Comment by YuanZi1501040205** [comment]
Where to download your data sets?

**Comment by kirthir** [comment]
can you pls specify the image format you are using

**Comment by jibikbam** [comment]
For those who do not have a 3D data, you could try some 3D MRI data from public datasets such as HCP, ADNI, UK Biobank, OASIS, ABCD, and OpenNeuro.

Regarding labels, I had a csv file consisting of integer numbers (label) for each sample.

Please let me know if you have further questions.
