### ISSUE TITLE
Hello, I have some question about your simple.

### ISSUE THREAD

**Issue by chenyifen12310** [jibikbam/CNN-3D-images-Tensorflow#5]
hello, I want to build a model to put my MRI image in your simple, my question is how to import my image ?Can you teach me?

![2017-10-14 10 31 06](https://user-images.githubusercontent.com/32772192/31576531-8504aa88-b0c2-11e7-9ed3-30d80b50c3b5.png)

**Comment by jibikbam** [comment]
There are public libraries to import medical images. For DICOMs, you could use pydicom or medpy. For NIFTI, you could use nibabel. Also, if you do not have a 3D medical data, I recommend trying with some MRI data from public datasets such as HCP, ADNI, UK Biobank, OASIS, ABCD, and OpenNeuro.
