### ISSUE TITLE
FC

### ISSUE THREAD

**Issue by CXSunshine** [jibikbam/CNN-3D-images-Tensorflow#9]
I want to know how you choose parameters fo FC layers.

**Comment by xingjianzhang1997** [comment]
Do you know how to form my data to adapt this code ?

**Comment by jibikbam** [comment]
Parameters for the last FC layers depends on how many classes you'd like to have for your task.

**Comment by jibikbam** [comment]
There are public libraries to import medical images. For DICOMs, you could use pydicom or medpy. For NIFTI, you could use nibabel. Also, if you do not have a 3D medical data, I recommend trying with some MRI data from public datasets such as HCP, ADNI, UK Biobank, OASIS, ABCD, and OpenNeuro.
